### ISSUE TITLE
Fails to open Gutenberg ePubs

### ISSUE THREAD

**Issue by chadananda** [Vaporbook/epub-parser#1]
Although the test ePub works fine, I get this same error trying to open any ePub from Project Gutenberg:

<pre>
[TypeError: Cannot read property '0' of undefined]
metadata element error: Cannot read property '0' of undefined
manifest element error: Cannot read property '0' of undefined
must throw this
</pre>

Here's an example book: 

https://dl.dropboxusercontent.com/u/382588/ocean2.0/development/gutenberg-710.epub

---

Seems this is where the error is thrown:

<pre><javascript>
        function parsePackageElements() {         

          // operates on global vars
          try {
              metadata = opf[opfPrefix+"metadata"][0];
          } catch(e) {
              console.log('metadata element error: '+e.message);
          }
          try {
              manifest = opf[opfPrefix+"manifest"][0];

          } catch (e) {
              console.log('manifest element error: '+e.message);
              console.log('must throw this');
              throw (e);
          }
          try {
              spine = opf[opfPrefix+"spine"][0];
          } catch(e) {
              console.log('spine element error: '+e.message);
              console.log('must throw this');
              throw (e);
          }
          try {
              guide = opf[opfPrefix+"guide"][0];
          } catch (e) {
              ;
          }
        }
</javascript></pre>

It looks like the manifest, spine and guide keys are expected to be prefixed with 'opf:' but they are not so in the object:

<pre>{ '$': 
   { 'xmlns:opf': 'http://www.idpf.org/2007/opf',
     'xmlns:dcterms': 'http://purl.org/dc/terms/',
     'xmlns:dc': 'http://purl.org/dc/elements/1.1/',
     'xmlns:xsi': 'http://www.w3.org/2001/XMLSchema-instance',
     xmlns: 'http://www.idpf.org/2007/opf',
     version: '2.0',
     'unique-identifier': 'id' },
  metadata: 
   [ { 'dc:rights': [Object],
       'dc:identifier': [Object],
       'dc:creator': [Object],
       'dc:title': [Object],
       'dc:language': [Object],
       'dc:subject': [Object],
       'dc:date': [Object],
       'dc:source': [Object],
       meta: [Object] } ],
  manifest: [ { item: [Object] } ],
  spine: [ { '$': [Object], itemref: [Object] } ],
  guide: [ { reference: [Object] } ] }
</pre>

**Comment by Vaporbook** [comment]
Thanks for catching this - the gutenberg files were indicating namespaced tags (ie "opf:manifest"), but they don't contain namespaced tags (the tag name is just "manifest"). Gutenberg should remove the xmlns:opf attribute from the package element to be compatible with a wider range of parsers, but I've put in a workaround to handle for it and confirmed it works on a few tests.
